---
- name: get pre-requisite packages
  package:
    name: 
      - git
      - make
    state: present

- name: Git checkout awx-operator
  git:
    repo: 'https://github.com/ansible/awx-operator.git'
    dest: /srv/checkout/awx-operator
    version: 1.1.3
    force: true

- name: export namespace=awx
  shell: |
    export NAMESPACE=awx
    kubectl create ns ${NAMESPACE}
    kubectl config set-context --current --namespace=$NAMESPACE
    cd /srv/checkout/awx-operator
    sudo make deploy

- name: Ansible check directory
  stat:
   path: /srv/awx
  register: awx_folder

- name: "Ansible Create directory if not exists"
  file:
   path: /srv/awx
   state: directory
   mode: 0755
   group: root
   owner: root
  when: awx_folder.stat.exists == false

- name: Create public-static-pvc.yaml
  copy:
    src: files/public-static-pvc.yaml 
    dest: /srv/awx/public-static-pvc.yaml
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Apply public-static-pvc.yaml
  shell: |
    kubectl apply -f /srv/awx/public-static-pvc.yaml -n awx 

- name: Create awx-instance-deployment.yml 
  copy:
    src: files/awx-instance-deployment.yml
    dest: /srv/awx/awx-instance-deployment.yml
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Apply awx-instance-deployment.yml
  shell: | 
    kubectl apply -f /srv/awx/awx-instance-deployment.yml -n awx
